### ISSUE TITLE
(unify) Update code style.

### ISSUE THREAD

**Issue by schmidtw** [xmidt-org/chronon#24]
## Fix code style

Using Go 1.20 or 1.21, run:

```bash
find . -name '*.go' -exec gofmt -s -w {} \;
```

This should update the formatting so it is compliant.

## Enable copyright checking in the action

In `.github.workflows/ci.yml` remove the line `style-skip: true`.

**Comment by johnabass** [comment]
The code style is correct, but this technique doesn't work for code in comment blocks due to some whitespace munging.  I've removed example code in comment blocks so that the style check should pass.

**Comment by johnabass** [comment]
Addressed by https://github.com/xmidt-org/chronon/pull/35
